
import BooleanModel.InvertedIndex;
import BooleanModel.indexer;
import BooleanModel.Result;
import BooleanModel.Stats;

import java.awt.*;
import java.io.*;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muham
 */
public class MainWindow extends javax.swing.JFrame {
    static String Path = System.getProperty("user.dir") + "\\src\\dataset\\";
    static indexer preprocess;
    static InvertedIndex index;
    static Result retrieved;
    static String Query; 
    static Stats stat;
    static int filecount = 50;
    /**
     * Creates new form MainWindow
     */
    
    public MainWindow() {
        initComponents();
        Resultpanel.setLayout(new javax.swing.BoxLayout(Resultpanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setBorder(null);
        String URL = System.getProperty("user.dir") + "\\src\\img\\pic.png";
        ImageIcon img = new ImageIcon(URL);
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbar = new java.awt.TextField();
        searchbutton = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultpanel = new javax.swing.JPanel();
        method = new javax.swing.JComboBox<>();
        heading = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        stats = new javax.swing.JLabel();
        indexing = new javax.swing.JLabel();
        options = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boolean Retrieval Model");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        searchbar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchbar.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        searchbar.setText("Search");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        getContentPane().add(searchbar);
        searchbar.setBounds(130, 130, 611, 27);

        searchbutton.setLabel("Go");
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbuttonMouseExited(evt);
            }
        });
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton);
        searchbutton.setBounds(770, 130, 172, 27);

        Resultpanel.setLayout(new javax.swing.BoxLayout(Resultpanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(Resultpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 919, 440);

        method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Boolean Query", "Proximity Query", "Pharse Query"}));
        getContentPane().add(method);
        method.setBounds(770, 170, 172, 32);

        heading.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Boolean Retrieval Model");
        getContentPane().add(heading);
        heading.setBounds(382, 16, 382, 57);

        author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        author.setText("<html><h4>By Muhammad Shahzaib<br/>  K163810</h4> </html>");
        getContentPane().add(author);
        author.setBounds(680, 60, 221, 50);

        stats.setBackground(new java.awt.Color(255, 255, 255));
        stats.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stats.setForeground(new java.awt.Color(0, 51, 255));
        stats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.setText("<html><u>Want some STATS? </u></html>");
        stats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsMouseClicked(evt);
            }
        });
        getContentPane().add(stats);
        stats.setBounds(980, 70, 235, 134);

        indexing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        indexing.setForeground(new java.awt.Color(0, 0, 255));
        indexing.setText("<html><u>reindex</u></html");
        indexing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indexingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                indexingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                indexingMouseExited(evt);
            }
        });
        getContentPane().add(indexing);
        indexing.setBounds(680, 180, 51, 17);

        options.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        options.setForeground(new java.awt.Color(0, 0, 255));
        options.setText("<html><u>Change Variables</u></html>");
        options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionsMouseExited(evt);
            }
        });
        getContentPane().add(options);
        options.setBounds(540, 180, 119, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void run(){
        retrieved = new Result();
        Query = searchbar.getText();
        String str = Query.toLowerCase().trim();
        if(method.getSelectedItem() == "Boolean Query"){
            splitor(str);
        }
        else
        if(method.getSelectedItem() == "Pharse Query" || method.getSelectedItem() == "Proximity Query"){
            for(String sword: preprocess.Stopword){
                str = str.replaceAll(" " + sword + " ", " ");
            }
            proximity(str);
        }
        print();
    }
    
    private void MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        JLabel selected = (JLabel)evt.getSource();
        selected.setForeground(Color.blue);
        String words[] = selected.getText().split(" ");
        String numb = words[2];
        String s = Path + "\\ShortStories\\" + numb  +  ".txt";
        story str = new story(s, retrieved.t);
        str.setVisible(true);
    } 
    
    private void MouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        JLabel selected = (JLabel)evt.getSource();
        selected.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Resultpanel.revalidate();
        Resultpanel.repaint();
    }
    
    private void MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        JLabel selected = (JLabel)evt.getSource();
        selected.setBorder(null);
        Resultpanel.revalidate();
        Resultpanel.repaint();
    }
    
    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
             run();
    }//GEN-LAST:event_searchbuttonMouseClicked

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
       run();
    }//GEN-LAST:event_searchbarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void searchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseEntered
        // TODO add your handling code here:
        Button sbutton = (Button) evt.getSource();
        sbutton.setBackground(Color.darkGray);
        sbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_searchbuttonMouseEntered

    private void searchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseExited
        // TODO add your handling code here:
        Button sbutton = (Button) evt.getSource();
        sbutton.setBackground(Color.LIGHT_GRAY);
        sbutton.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_searchbuttonMouseExited

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void statsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseClicked
        // TODO add your handling code here:
        stat.calculation();
        stats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Set Statistics:", 
                                                                            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                                                            javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                                                            new java.awt.Font("Tahoma", 0, 15)));
        stats.setFont(new Font(stats.getFont().getName(), Font.PLAIN, 11));
        stats.setForeground(Color.BLACK);
        stats.setText(stat.getstats());
    }//GEN-LAST:event_statsMouseClicked

    private void indexingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexingMouseClicked
        // TODO add your handling code here:
        index = preprocess.makeindex();
    }//GEN-LAST:event_indexingMouseClicked

    private void indexingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexingMouseEntered
        // TODO add your handling code here:
        indexing.setForeground(Color.darkGray);
        
    }//GEN-LAST:event_indexingMouseEntered

    private void indexingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexingMouseExited
        // TODO add your handling code here:
        indexing.setForeground(Color.blue);
    }//GEN-LAST:event_indexingMouseExited

    private void optionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMouseEntered
        // TODO add your handling code here:
        options.setForeground(Color.darkGray);
    }//GEN-LAST:event_optionsMouseEntered

    private void optionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMouseExited
        // TODO add your handling code here:
        options.setForeground(Color.blue);
    }//GEN-LAST:event_optionsMouseExited

    private void optionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMouseClicked
        // TODO add your handling code here:
        Popup pop = new Popup(this, true, filecount);
        pop.setVisible(true);
        File tmpDir = new File(pop.returnpath());
        if(tmpDir.exists()){
            Path = pop.returnpath();
        }
        filecount = pop.returnfilecount();
        change();
        pop.dispose();
    }//GEN-LAST:event_optionsMouseClicked
          
    public void change(){
        preprocess.path = Path;
        stat.path = Path;
        preprocess.filecount = filecount;
        stat.filecount = filecount;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        preprocess = new indexer(filecount);
        index = preprocess.makeindex();
        Path = preprocess.path;
        stat = new Stats(filecount);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }
    
    public static void proximity(String query){
        query = query.trim();
        int k = query.split(" ").length * 2;
        if(query.contains("/")){
            k = Integer.parseInt(query.substring(query.lastIndexOf("/") + 1));
            query = query.replaceAll("\\d", "");
            query = query.replace("/", "");
            query = query.trim();
        }
        splitor(query);
        filter(k);
    }
    
    public static void filter(int k){
        Result r = new Result();
        r.t = (LinkedList<String>) retrieved.t.clone();
        r.doclist = (LinkedList<Integer>) retrieved.doclist.clone();
        
        String s1 = retrieved.t.get(0);
        for(int i=1; i<retrieved.t.size(); i++){
            String s2 = retrieved.t.get(i);
            int Array[];
            LinkedList <Integer> arr = new LinkedList();
            for(int l: r.doclist){
                LinkedList<Integer> p1 = index.terms.get(s1).list[l].positions; 
                LinkedList<Integer> p2 = index.terms.get(s2).list[l].positions;
                for(int x: p1){
                    int ll=0;
                    for(int y: p2){
                        int prox = Math.abs(x-y);
                        if(prox <= k+1 ){
                            if(!(arr.contains(l))){
                                arr.add(l);
                                ll=-1;
                                break;
                            }
                        }
                    }
                    if(ll == -1){
                        break;
                    }
                }
            }
            r.doclist = (LinkedList<Integer>) arr.clone();
        }
        retrieved = r;
    }
    
    public void print(){
        Rank();
        Resultpanel.removeAll();
        Resultpanel.revalidate();
        Resultpanel.repaint();
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", 
                                                                            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                                                            javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                                                            new java.awt.Font("Tahoma", 0, 36)));
        JLabel count = new JLabel();
        count.setText("Documents in result: " + retrieved.doclist.size());
        count.setFont(new Font(count.getFont().getName(), Font.PLAIN, 14));
        count.setForeground(Color.GRAY);
        Resultpanel.add(count);
        JLabel result[] = new JLabel[retrieved.doclist.size()];
        for(int i=0; i<retrieved.doclist.size(); i++){
            result[i] = new JLabel();
            result[i].setVisible(true);
            int docID = retrieved.doclist.get(i) + 1;
            String answer = "<html><b>Document #: " + String.valueOf(docID) + " </b><br />";
            answer = answer +  "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
                     +  index.stories[docID-1].getstory() + "<br /><br /></html>";
            JLabel tf = new JLabel();
            String tfcount = "<html>Term Frequences:<br/>";
            for(String s: retrieved.t){
                    tfcount = tfcount + s + "->" + index.terms.get(s).gettf(retrieved.doclist.get(i)) + "<br/>";
            }
            tfcount = tfcount + "<br />"
                    + "******************************************************************************************************************"
                    + "********************************************************"
                    + "<br /></html>";
            tf.setText(tfcount);
            result[i].setText(answer);
            result[i].setFont(new Font(result[i].getFont().getName(), Font.PLAIN, 14));
            
            result[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    MouseClicked(evt);
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    MouseEntered(evt);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    MouseExited(evt);
                }
            });
            Resultpanel.add(result[i]);
            Resultpanel.add(tf);
            
        }  
        Resultpanel.revalidate();
    }
    
    public void Rank(){
        LinkedList<Integer> [] Rank = new LinkedList[2];
        LinkedList<Integer> order = new LinkedList();
        Rank[0] = new LinkedList();
        Rank[0] =  (LinkedList) retrieved.doclist.clone();
        Rank[1] = new LinkedList();
        int count = 0;
        for(int i:Rank[0]){
            int sum =0;
            for(String s: retrieved.t){
                sum += index.terms.get(s).gettf(i);
            }
            Rank[1].add(sum);
            count++;
        }
        while(Rank[0].size() > 0){
            int min = Collections.max(Rank[1]);
            int index = Rank[1].indexOf(min);
            order.add(Rank[0].get(index));
            Rank[1].remove(index);
            Rank[0].remove(index);
        }
        retrieved.doclist = order;
        
    }
    
    public static void splitor(String query){
        query = query.replaceAll("[.,<>(){}\"?!'`~@#$%^&*;:/\\\\\\[\\]]+", "");
        query = query.replaceAll("[-]+", " and ");
        int result1[];
        int result2[] = {};
        int k=0;
        String subQuery[] = query.split(" or ");
        for (String subQuery1 : subQuery){
            result1 = splitand(subQuery1);
            if(k == 0){
                result2 = result1.clone();
                result2 = or(result1, result2);
            }else{
                result2 = or(result1, result2);
            }
            k++;
        }
        Arrays.sort(result2);
        for(int i:result2){
            retrieved.doclist.add(i);
        }
    }
    
    public static int[] splitand(String query){
        int result1[];
        int result2[] = {};
        int k=0;
        String subQuery[] = query.split(" and ");
        for (String subQuery1 : subQuery){
            String ss[] = subQuery1.split(" ");
            subQuery1 = "";
            for(String s: ss){
                if(!(preprocess.Stopword.contains(s))){
                    subQuery1 = subQuery1 + " " + s;
                }
            }
            result1 = solve(subQuery1);
            if(k == 0){
                result2 = result1.clone();
                result2 = and(result1, result2);
            }else{
                result2 = and(result1, result2);
            }
            k++;
        }
        return result2;
    }
    
    public static int [] solve(String query){
        int result[] = {};
        query = query.replaceAll("not not ", "");
        query = query.trim();
        if(query.contains("not ")){
            query = query.replace("not ", "");
            query = query.trim();
            if(query.contains(" ")){
                query = query.replace(" ", " and not ");
                query = "not " + query;
                result = splitand(query);
            }
            else{
                if(index.terms.containsKey(query)){
                    result = index.terms.get(query).getNOTdocID();
                    retrieved.t.add(query);
                }
            }
        }
        else{
            query = query.trim();
            if(query.contains(" ")){
                query = query.replace(" ", " and ");
                result = splitand(query);
            }
            else{
                if(index.terms.containsKey(query)){
                    result = index.terms.get(query).getdocID();
                    retrieved.t.add(query);
                }
            }
        }
        return result;
    }
    
    public static int[] and(int []a, int [] b){
        LinkedList<Integer> result = new LinkedList();
        int c[], d[];
        if(a.length > b.length){
            c = a;
            d = b;
        }
        else{
            c = b;
            d = a;
        }
        java.util.List<Integer> list = Arrays.stream(c).boxed().collect(Collectors.toList());
        
        for(int i: d){
            if(list.contains(i)){
                result.add(i);
            }
        }
        return result.stream().mapToInt(k->k).toArray();
    }
    
    public static int[] or(int []a, int [] b){
        LinkedList<Integer> result = new LinkedList();
        int c[], d[];
        if(a.length > b.length){
            c = a;
            d = b;
        }
        else{
            c = b;
            d = a;
        }
        for(int i:c){
            result.add(i);
        }
        for(int i: d){
            if(!(result.contains(i))){
                result.add(i);
            }
        }
        return result.stream().mapToInt(k->k).toArray();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Resultpanel;
    public javax.swing.JLabel author;
    public javax.swing.JLabel heading;
    private javax.swing.JLabel indexing;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> method;
    private javax.swing.JLabel options;
    public java.awt.TextField searchbar;
    public java.awt.Button searchbutton;
    private javax.swing.JLabel stats;
    // End of variables declaration//GEN-END:variables
}
