
import java.awt.Font;
import java.io.*;
import java.util.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muham
 */
public class story extends javax.swing.JFrame {
    public String Path;
    public LinkedList terms;
    /**
     * Creates new form story
     * @param s
     */
    public story(String s, LinkedList<String> t) {
        terms = new LinkedList();
        terms = (LinkedList) t.clone();
        Path = s;
        initComponents();
        Storylines.setLayout(new javax.swing.BoxLayout(Storylines, javax.swing.BoxLayout.PAGE_AXIS));
        String URL = System.getProperty("user.dir") + "\\src\\img\\pic.png";
        ImageIcon img = new ImageIcon(URL); //E:\\Semester 6\\IR\\New Folder\\Boolean_Model\\src\\img\\pic.png
        this.setIconImage(img.getImage());
        writter();
    }
    
    public void writter(){
        Scanner x = null;
        try{
            x= new Scanner(new File(Path), "UTF-8");
        }
        catch(FileNotFoundException e){
            System.out.println(e);
        }
        int i=0;
        while(x.hasNextLine()){
            String str;
            str = x.nextLine();
            String words[] = str.split(" ");
            String write = "<html>" ;
            for(String s:words){
                String check = preprocess(s);
                if(terms.contains(check)){
                    write = write + "<span style=\"background-color: #FFFF00\"><b>" + s + "</b></span>" + " ";
                }
                else{
                    write = write + s + " ";
                }
                i++;
                if(i == 30){
                    write = write + "<br/>";
                    i=0;
                }
            }
            write = write + " " + "</html>";
            JLabel line = new JLabel();
            line.setFont(new Font(line.getFont().getName(), Font.PLAIN, 15));
            line.setText(write);
            Storylines.add(line);
        }    
        Storylines.revalidate();
    }
    
    private String preprocess(String s){
        String processed;
        processed = s.replaceAll("[.,<>(){}\"?!'`~@#$%^&*;:/\\\\\\[\\]]+","");
        processed = processed.toLowerCase();
        return processed;
    }
    
    public story(){
        initComponents();
        String URL = System.getProperty("user.dir") + "\\src\\img\\pic.png";
        ImageIcon img = new ImageIcon(URL); //E:\\Semester 6\\IR\\New Folder\\Boolean_Model\\src\\img\\pic.png
        this.setIconImage(img.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StoryScroll = new javax.swing.JScrollPane();
        Storylines = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Story");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(20, 10));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Storylines.setName("Story"); // NOI18N
        Storylines.setLayout(new javax.swing.BoxLayout(Storylines, javax.swing.BoxLayout.LINE_AXIS));
        StoryScroll.setViewportView(Storylines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StoryScroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StoryScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:                      
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new story().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane StoryScroll;
    private javax.swing.JPanel Storylines;
    // End of variables declaration//GEN-END:variables
}
